/**
 * env-registry.ts — RIVET_* 环境变量注册表（自动生成）。
 *
 * name/defaultHint/files 由 scripts/gen-env-registry.ts 生成，勿手改；
 * description 字段人工维护，重新生成时按 name 保留。
 * 最后生成：2026-09-23T01:54:24.565Z
 * 共 222 个变量。
 *
 * 每个条目含：名称 / 默认值提示 / 引用文件 / 简要说明。
 * 当源码中新增 RIVET_* 引用但注册表未同步时，
 * assembly-audit.test.ts 的 env completeness 测试会失败（双向检查）。
 */

export interface EnvRegistryEntry {
  /** 环境变量名（含 RIVET_ 前缀） */
  name: string
  /** 从源码 ??/|| 推断的默认值，若无则为空 */
  defaultHint: string
  /** 引用该变量的源文件列表（相对 src/） */
  files: string[]
  /** 简要说明（人工维护，重新生成时保留） */
  description: string
}

export const ENV_REGISTRY: EnvRegistryEntry[] = [
  {
    name: 'RIVET_ACCOUNT_ANON_KEY',
    defaultHint: 'DEFAULT_PUBLISHABLE_KEY',
    files: ['auth/account.ts'],
    description: '',
  },
  {
    name: 'RIVET_ACCOUNT_API',
    defaultHint: 'DEFAULT_ACCOUNT_API',
    files: ['auth/account.ts'],
    description: '',
  },
  {
    name: 'RIVET_ADAPTIVE_MEMORY',
    defaultHint: '',
    files: ['memory/adaptive-stm.ts'],
    description: '意图门控 STM：shadow 仅评估不注入；on/1 经 appendixDelta 注入；off/0 关闭。',
  },
  {
    name: 'RIVET_ADVISORY_EFFICACY_SPAN',
    defaultHint: '',
    files: ['agent/advisory-bus.ts', 'agent/__tests__/advisory-efficacy-sort.test.ts'],
    description: '效力对 advisory 有效优先级的最大调整幅度（±），0 关闭效力排序',
  },
  {
    name: 'RIVET_ADVISORY_HOLDOUT',
    defaultHint: '',
    files: ['agent/loop.ts'],
    description: 'advisory holdout 对照组开关（P1a 核销闭环）',
  },
  {
    name: 'RIVET_ADVISORY_LIFT_CONSUMER',
    defaultHint: '',
    files: ['agent/loop.ts'],
    description: '',
  },
  {
    name: 'RIVET_AMBIGUOUS_WIDTH',
    defaultHint: '\'\'',
    files: ['tui/width.ts', 'tui/engine/__tests__/live-engine-ghost-render.test.ts', 'tui/__tests__/width.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_AMNESIA_SHADOW',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_APPENDIX_DELTA',
    defaultHint: '',
    files: ['agent/create-agent-config.ts'],
    description: '',
  },
  {
    name: 'RIVET_APPENDIX_TRACE',
    defaultHint: '',
    files: ['agent/appendix-trace.ts', 'agent/__tests__/appendix-trace.test.ts'],
    description: '设为 1 把逐请求的附录渲染结果落到 <会话目录>/appendix-trace.jsonl（默认关；自述层此前零留痕，事后无法取一份模型真实看到的块）',
  },
  {
    name: 'RIVET_APPLY_PATCH_VERIFY',
    defaultHint: '',
    files: ['tools/apply-patch.ts'],
    description: '',
  },
  {
    name: 'RIVET_APPROVAL_TIMEOUT_MS',
    defaultHint: '',
    files: ['server/session-manager.ts'],
    description: '',
  },
  {
    name: 'RIVET_ASCII_UI',
    defaultHint: '',
    files: ['tui/term-caps.ts', 'tui/format/__tests__/side-question.test.ts', 'tui/engine/__tests__/app-core.test.ts', 'tui/__tests__/format-plan-picker.test.ts', 'tui/__tests__/format-welcome.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_AST_EDIT_VERIFY',
    defaultHint: '',
    files: ['tools/ast-edit.ts'],
    description: '',
  },
  {
    name: 'RIVET_AST_EXCLUDE',
    defaultHint: '',
    files: ['tools/ast-shared.ts', 'tools/__tests__/ast-shared.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_AST_SCAN_TIMEOUT_MS',
    defaultHint: '',
    files: ['tools/ast-shared.ts', 'tools/__tests__/ast-edit.test.ts', 'tools/__tests__/ast-grep.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_ASYNC_COPILOT',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_BROWSER_ALLOWLIST',
    defaultHint: '\'\'',
    files: ['tools/browser.ts', 'tools/browser-debug/tool.ts'],
    description: '',
  },
  {
    name: 'RIVET_BROWSER_DEBUG',
    defaultHint: '',
    files: ['bootstrap.ts'],
    description: '',
  },
  {
    name: 'RIVET_BROWSER_URL',
    defaultHint: '',
    files: ['tools/browser-debug/tool.ts'],
    description: '',
  },
  {
    name: 'RIVET_BUNDLED_GIT_DIR',
    defaultHint: '',
    files: ['platform.ts'],
    description: '',
  },
  {
    name: 'RIVET_BUNDLED_PLUGINS_DIR',
    defaultHint: '',
    files: ['server/plugin-api.ts', 'server/__tests__/plugin-api.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_BUNDLED_RIPGREP_DIR',
    defaultHint: '',
    files: ['tools/grep.ts'],
    description: '',
  },
  {
    name: 'RIVET_BUNDLED_SKILLS_DIR',
    defaultHint: '',
    files: ['skills/skill-loader.ts'],
    description: '',
  },
  {
    name: 'RIVET_CANCEL_REST',
    defaultHint: '',
    files: ['agent/batch-short-circuit.ts', 'agent/__tests__/batch-short-circuit.test.ts'],
    description: 'delegateBatch 聚合策略（first_success/quorum）中途达标后短路取消剩余兄弟 worker，默认开；设 0/false/off/no 关闭',
  },
  {
    name: 'RIVET_CAPABILITY',
    defaultHint: '',
    files: ['tools/default-registry.ts', 'tools/__tests__/tool-preset.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CLAIM_AUDIT',
    defaultHint: '',
    files: ['agent/claim-audit.ts', 'agent/__tests__/claim-audit.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CLI_DISCOVER',
    defaultHint: '',
    files: ['tools/default-registry.ts'],
    description: '',
  },
  {
    name: 'RIVET_COMPUTER_USE',
    defaultHint: '',
    files: ['bootstrap.ts', 'main.ts', 'server/config-routes.ts'],
    description: '',
  },
  {
    name: 'RIVET_COMPUTER_USE_AUTOMOUNT',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_CONFIG_PATH',
    defaultHint: '',
    files: ['tui/__tests__/settings-persist.test.ts', 'tui/__tests__/slash-commands.test.ts', 'tools/__tests__/generate-image.test.ts', 'tools/__tests__/tool-preset.test.ts', 'server/__tests__/config-routes.test.ts', 'server/__tests__/image-gen-model-routes.test.ts', 'server/__tests__/session-manager.test.ts', 'server/__tests__/vision-model-onboarding-routes.test.ts', 'plugins/__tests__/integration/git-source-mirror-fallback.test.ts', 'config/paths.ts', 'config/__tests__/config-cli.test.ts', 'config/__tests__/config-load-error.test.ts', 'config/__tests__/config-schema-integration.test.ts', 'config/__tests__/config-watcher.test.ts', 'config/__tests__/image-gen-model.test.ts', 'config/__tests__/layered-config.test.ts', 'config/__tests__/manager-clear-api-key.test.ts', 'config/__tests__/manager-deepseek-vision-exp-retirement.test.ts', 'config/__tests__/manager-editor.test.ts', 'config/__tests__/manager-fetch-search.test.ts', 'config/__tests__/manager-permission-dirs.test.ts', 'config/__tests__/manager-profile-persist.test.ts', 'config/__tests__/manager-provider.test.ts', 'config/__tests__/manager-routing.test.ts', 'config/__tests__/manager-shell.test.ts', 'config/__tests__/manager-ui.test.ts', 'config/__tests__/manager-vision-model.test.ts', 'config/__tests__/model-save-semantics.test.ts', 'config/__tests__/preset-model-backfill.test.ts', 'config/__tests__/provider-advanced.test.ts', 'config/__tests__/provider-cli.test.ts', 'config/__tests__/provider-keys-file-migration.test.ts', 'config/__tests__/provider-keys-store.test.ts', 'config/__tests__/provider-keys.test.ts', 'config/__tests__/provider-onboarding-e2e.test.ts', 'config/__tests__/runtime-lean-aspect.test.ts', 'config/__tests__/runtime-lean.test.ts', 'config/__tests__/secrets-store.test.ts', 'agent/__tests__/config-watcher-release.test.ts', '__tests__/bootstrap.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CONFIG_WATCH',
    defaultHint: '',
    files: ['config/config-watcher.ts', 'config/__tests__/config-watcher.test.ts', 'agent/__tests__/config-watcher-release.test.ts'],
    description: '=0 关闭 config HMR 热更（config-watcher 不 watch 配置文件）',
  },
  {
    name: 'RIVET_CONTROL_PLANE',
    defaultHint: '',
    files: ['agent/control-plane-adapters.ts'],
    description: '',
  },
  {
    name: 'RIVET_CPU_POOL',
    defaultHint: '',
    files: ['workers/cpu-pool.ts', 'workers/__tests__/cpu-pool.test.ts', 'server/__tests__/disable-cpu-pool.ts'],
    description: '',
  },
  {
    name: 'RIVET_CPU_POOL_IDLE_MS',
    defaultHint: '',
    files: ['workers/cpu-pool.ts'],
    description: '',
  },
  {
    name: 'RIVET_CROSS_SESSION_CLAIMS',
    defaultHint: '',
    files: ['agent/cross-session-memory-config.ts', 'agent/__tests__/cross-session-killswitch.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CROSS_SESSION_EVENTS',
    defaultHint: '',
    files: ['agent/cross-session-memory-config.ts', 'agent/__tests__/cross-session-killswitch.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CROSS_SESSION_INJECT',
    defaultHint: '',
    files: ['agent/cross-session-memory-config.ts', 'agent/__tests__/cross-session-killswitch.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_ALLOW_LOCKED',
    defaultHint: '',
    files: ['pro/computer-use/tool.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_AX_OBSERVER',
    defaultHint: '',
    files: ['pro/computer-use/ax-observer.ts', 'pro/computer-use/__tests__/cdp-tool-routing.test.ts', 'pro/computer-use/__tests__/tool.test.ts', 'pro/computer-use/__tests__/user-yield.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_AX_OBSERVER_PATH',
    defaultHint: '',
    files: ['pro/computer-use/ax-observer.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_BROWSER_POLICY',
    defaultHint: '',
    files: ['pro/computer-use/browser-policy.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_CDP',
    defaultHint: '',
    files: ['pro/computer-use/tool.ts', 'pro/computer-use/__tests__/tool.test.ts', 'pro/computer-use/__tests__/user-yield.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_CDP_URL',
    defaultHint: '',
    files: ['pro/computer-use/cdp/chrome.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_COM',
    defaultHint: '',
    files: ['pro/computer-use/windows-uia-com.ts', 'pro/computer-use/__tests__/windows-driver.test.ts', 'pro/computer-use/__tests__/windows-uia-com.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_FEEDBACK',
    defaultHint: '',
    files: ['pro/computer-use/tool.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_HOST',
    defaultHint: '',
    files: ['pro/computer-use/script-host.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_JOURNAL',
    defaultHint: '',
    files: ['pro/computer-use/journal.ts', 'pro/computer-use/tool.ts', 'pro/computer-use/__tests__/cdp-tool-routing.test.ts', 'pro/computer-use/__tests__/tool.test.ts', 'pro/computer-use/__tests__/user-yield.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_OVERLAY',
    defaultHint: '',
    files: ['pro/computer-use/tool.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_PIXEL_DIFF',
    defaultHint: '',
    files: ['pro/computer-use/tool.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_YIELD_MS',
    defaultHint: '',
    files: ['tools/__tests__/bash-yield-wiring.test.ts', 'system/user-idle.ts', 'pro/computer-use/tool.ts'],
    description: '',
  },
  {
    name: 'RIVET_CU_YIELD_WATCH_MS',
    defaultHint: '',
    files: ['tools/bash-yield.ts', 'tools/__tests__/bash-yield-watch.test.ts', 'tools/__tests__/bash-yield-wiring.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_CVM_VECTOR',
    defaultHint: '',
    files: ['agent/hooks/cognitive-capsule-router.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEAD_END_DETECTOR',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG',
    defaultHint: '',
    files: ['bootstrap.ts', 'main.ts', 'utils/debug.ts', 'tui/engine/image-tool.ts', 'tui/engine/__tests__/image-tool.test.ts', 'skills/skill-loader.ts', 'api/__tests__/openai-client-tool-stream-log.test.ts', 'agent/__tests__/deliver-task.test.ts', 'agent/__tests__/interrupt-marker.test.ts', 'agent/__tests__/tool-pipeline.test.ts', '__tests__/assembly-audit.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_ORPHAN',
    defaultHint: '',
    files: ['context/resume-preflight.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_RAW_SSE',
    defaultHint: '',
    files: ['api/openai-client.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_RENDER',
    defaultHint: '',
    files: ['server/session-persistence.ts', 'server/session-routes.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_TELEMETRY',
    defaultHint: '',
    files: ['tui/engine/perf-monitor.ts', 'agent/telemetry-writer.ts', 'agent/__tests__/telemetry-writer.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_TOOL_INPUT',
    defaultHint: '',
    files: ['agent/tool-pipeline.ts', 'agent/__tests__/tool-pipeline.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEBUG_TOOL_STREAM',
    defaultHint: '',
    files: ['api/openai-client.ts'],
    description: '',
  },
  {
    name: 'RIVET_DECISIONS_INJECT',
    defaultHint: '',
    files: ['agent/decisions-experiment.ts'],
    description: 'decisions 通道注入：默认/0 关，1 强制开（确定性复现用），experiment 按会话 90/10 分组跑 holdout 实验。该分支曾因 session-state 空壳恒真而不可达，开启是未度量的行为变更，退出阈值见 decisions-experiment.ts',
  },
  {
    name: 'RIVET_DESKTOP',
    defaultHint: '',
    files: ['pro/__tests__/register-gate.test.ts', 'config/pro-license.ts', 'config/__tests__/pro-license.test.ts'],
    description: '由桌面端 Tauri 注入（CLI 无此变量），Pro 授权判定的分流开关：置位走桌面硬 gate（只认同样由 Rust 注入的 RIVET_PRO），缺席走 CLI 软 gate（config > env > file 三路径）',
  },
  {
    name: 'RIVET_DESKTOP_DIR',
    defaultHint: 'join(rivetHome(',
    files: ['diagnostics/__tests__/log-locations.test.ts', 'config/paths.ts'],
    description: '',
  },
  {
    name: 'RIVET_DESKTOP_SESSION_DIR',
    defaultHint: 'join(desktopDir(',
    files: ['config/paths.ts'],
    description: '',
  },
  {
    name: 'RIVET_DEV_CORS_ORIGINS',
    defaultHint: '',
    files: ['server/cors.ts'],
    description: '',
  },
  {
    name: 'RIVET_DISK_WARN_MB',
    defaultHint: '',
    files: ['utils/disk-space.ts', 'utils/__tests__/disk-space.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_EDIT_SMART_ROUTING',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_EFFORT_ROUTING',
    defaultHint: '',
    files: ['agent/__tests__/effort-routing.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_EMBEDDING_API_KEY',
    defaultHint: 'env.DEEPSEEK_API_KEY',
    files: ['search/embedding-provider.ts'],
    description: '',
  },
  {
    name: 'RIVET_EMBEDDING_BASE_URL',
    defaultHint: '(env.OPENAI_API_KEY ? \'https://api.opena',
    files: ['search/embedding-provider.ts'],
    description: '',
  },
  {
    name: 'RIVET_EMBEDDING_MODEL',
    defaultHint: '\'text-embedding-3-small\'',
    files: ['search/embedding-provider.ts'],
    description: '',
  },
  {
    name: 'RIVET_EMBEDDING_TIMEOUT',
    defaultHint: '\'\'',
    files: ['search/embedding-provider.ts'],
    description: '',
  },
  {
    name: 'RIVET_ESBUILD_LOAD_TIMEOUT',
    defaultHint: '\'\'',
    files: ['tools/syntax-check.ts', 'tools/__tests__/syntax-check.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_EXTERNAL_CLAIM_TRACKING',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts', 'agent/__tests__/create-runtime-hooks.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_EXTERNAL_SCAN_MS',
    defaultHint: '',
    files: ['server/session-manager.ts'],
    description: '',
  },
  {
    name: 'RIVET_FETCH_PIN',
    defaultHint: '',
    files: ['tools/net/http-fetch.ts', 'tools/net/__tests__/http-fetch.test.ts', 'mcp/oauth/__tests__/request-security.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_FETCH_PLAYWRIGHT',
    defaultHint: '',
    files: ['tools/web-fetch/build-options.ts'],
    description: '',
  },
  {
    name: 'RIVET_FETCH_SKIP_COMPILE',
    defaultHint: '\'unset\'',
    files: ['repo/__tests__/native-resolver.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_FORCE_RECOVERY_CLI',
    defaultHint: '',
    files: ['main.ts'],
    description: '',
  },
  {
    name: 'RIVET_FRAME_TELEMETRY',
    defaultHint: '',
    files: ['agent/frame-telemetry.ts', 'agent/__tests__/frame-telemetry.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_GATE_BLOCK_GUARD',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_GENERAL_LEDGER_REMINDER',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_GIT_BASH_PATH',
    defaultHint: '',
    files: ['platform.ts', 'server/__tests__/host-probe-prewarm.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_GIT_CLEAR_GUARD',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_GIT_PATH',
    defaultHint: '',
    files: ['tools/__tests__/apply-patch-abort.test.ts', 'tools/__tests__/spawn-git.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_GOAL_PLAN_AUTO_APPROVE_MS',
    defaultHint: '',
    files: ['tui/plan-auto-approve.ts', 'server/serve.ts'],
    description: '',
  },
  {
    name: 'RIVET_HEADLESS_MAX_TURNS',
    defaultHint: '',
    files: ['main.ts'],
    description: '非 goal 模式下 -p 一次提示的最大轮数（默认 15）；benchmark/eval 多文档任务可调高',
  },
  {
    name: 'RIVET_HOME',
    defaultHint: '',
    files: ['tui/engine/__tests__/connect-draft-engine.test.ts', 'tui/engine/__tests__/connect-wizard-list.test.ts', 'tui/engine/__tests__/overlay-deactivate-regression.test.ts', 'tui/__tests__/account-status.test.ts', 'tui/__tests__/history-async.test.ts', 'tui/__tests__/updater.test.ts', 'tui/__tests__/zen-command.test.ts', 'tools/__tests__/tool-preset.test.ts', 'server/__tests__/config-routes-keys.test.ts', 'server/__tests__/config-routes-provider-hot-reload.test.ts', 'server/__tests__/config-routes-put-model-probe.test.ts', 'server/__tests__/config-routes-zen.test.ts', 'server/__tests__/config-routes.test.ts', 'server/__tests__/mcp-hot-add.test.ts', 'server/__tests__/mcp-inject-tools.test.ts', 'server/__tests__/mcp-presets.test.ts', 'server/__tests__/mcp-server-config.test.ts', 'server/__tests__/path-grants-routes.test.ts', 'server/__tests__/plugin-api.test.ts', 'server/__tests__/plugin-session-cache.test.ts', 'server/__tests__/project-docs-routes.test.ts', 'server/__tests__/recordings-distill-route.test.ts', 'server/__tests__/scratch-route.test.ts', 'server/__tests__/serve-model-spec.test.ts', 'server/__tests__/serve-switch-model.test.ts', 'server/__tests__/session-manager.test.ts', 'server/__tests__/session-routes.test.ts', 'server/__tests__/trust-api.test.ts', 'server/__tests__/worker-log-route.test.ts', 'prompt/__tests__/block-policy.test.ts', 'prompt/__tests__/engine.test.ts', 'prompt/__tests__/volatile-cache.test.ts', 'pro/computer-use/__tests__/tool.test.ts', 'pro/__tests__/register-gate.test.ts', 'plugins/__tests__/design-plugin-lib.test.ts', 'plugins/__tests__/plugin-installer.test.ts', 'plugins/__tests__/plugin-loader.test.ts', 'mcp/oauth/__tests__/connector.test.ts', 'mcp/oauth/__tests__/request-security.test.ts', 'mcp/__tests__/manager.test.ts', 'diagnostics/log-locations.ts', 'diagnostics/__tests__/log-locations.test.ts', 'diagnostics/__tests__/logs-cli.test.ts', 'config/paths.ts', 'config/__tests__/config-cli.test.ts', 'config/__tests__/config-watcher.test.ts', 'config/__tests__/manager-profile-persist.test.ts', 'config/__tests__/pro-license.test.ts', 'config/__tests__/profile.test.ts', 'config/__tests__/project-trust.test.ts', 'config/__tests__/remove-model.test.ts', 'config/__tests__/workspace-config.test.ts', 'cli/__tests__/prompt-version-warning.test.ts', 'auth/__tests__/login-flow.test.ts', 'api/deepseek-platform-client.ts', 'agent/__tests__/config-watcher-release.test.ts', 'agent/__tests__/session-cd-rebuild-stores.test.ts', 'agent/__tests__/session-cd.test.ts', 'agent/__tests__/worker-session.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_HOOKS_DISABLED',
    defaultHint: '',
    files: ['config/profile.ts', 'agent/__tests__/loop-factory.test.ts'],
    description: '逗号分隔的 CVM 管线禁用 hook id 列表，优先于 config.hooks.disabled（热更见 config-watcher）',
  },
  {
    name: 'RIVET_HYPERLINKS',
    defaultHint: '',
    files: ['tui/engine/ansi.ts'],
    description: '',
  },
  {
    name: 'RIVET_IDLE_COMPACTION',
    defaultHint: '',
    files: ['agent/loop.ts'],
    description: '',
  },
  {
    name: 'RIVET_IDLE_COMPACTION_MS',
    defaultHint: '',
    files: ['agent/loop.ts'],
    description: '',
  },
  {
    name: 'RIVET_IDLE_COMPACTION_RATIO',
    defaultHint: '',
    files: ['agent/loop.ts', 'agent/__tests__/loop-idle-compaction.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_IMAGES',
    defaultHint: '',
    files: ['tui/engine/ansi.ts'],
    description: '',
  },
  {
    name: 'RIVET_IMPORT_RESOURCE',
    defaultHint: '',
    files: ['tools/default-registry.ts', 'tools/__tests__/tool-preset.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_INTENT_ANCHOR',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_INTENT_ANCHOR_STALE',
    defaultHint: '',
    files: ['agent/hooks/__tests__/intent-anchor-hook.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_INTENT_ANCHOR_TURNS',
    defaultHint: '',
    files: ['agent/hooks/__tests__/intent-anchor-hook.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_INTERRUPT_MARKER',
    defaultHint: '',
    files: ['config/interrupt-marker-config.ts', 'agent/__tests__/interrupt-marker.test.ts'],
    description: '打断留痕开关，默认开；设 0/false/off/no 关闭（等价 config agent.interruptMarker=false）——关闭时用户 Stop 撤回未答的 user 消息（旧行为）',
  },
  {
    name: 'RIVET_ISSUE_',
    defaultHint: '',
    files: ['tools/__tests__/bash-windows-smoke.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_JOB_LAUNCHER',
    defaultHint: '',
    files: ['tools/process-kill.ts', 'tools/__tests__/process-kill.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_JOB_MAX_MS',
    defaultHint: '\'\'',
    files: ['tools/job-store.ts'],
    description: '',
  },
  {
    name: 'RIVET_LANG',
    defaultHint: '',
    files: ['tui/cockpit/labels.ts'],
    description: 'UI language for the Cockpit dashboard (zh | en; regional prefixes like zh-CN / en-US accepted, unknown values fall back to zh).',
  },
  {
    name: 'RIVET_LANGUAGE_ANCHOR',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_LEAN',
    defaultHint: '',
    files: ['repo/__tests__/meridian-backfill.test.ts', 'config/runtime-lean.ts', 'config/__tests__/runtime-lean-aspect.test.ts', 'config/__tests__/runtime-lean.test.ts'],
    description: 'Runtime lean profile (minimal tools, lean prompt, no embeddings, no Meridian startup backfill, tighter session pool).',
  },
  {
    name: 'RIVET_LEAN_ASPECT',
    defaultHint: '',
    files: ['config/runtime-lean.ts', 'config/__tests__/runtime-lean-aspect.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_LEAN_AUTO',
    defaultHint: '',
    files: ['config/__tests__/runtime-lean.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_LEAVE_MARK',
    defaultHint: '',
    files: ['tools/default-registry.ts'],
    description: '',
  },
  {
    name: 'RIVET_MAX_EVENTS',
    defaultHint: '',
    files: ['server/session-manager.ts', 'server/__tests__/session-history-page.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_MAX_WORKERS',
    defaultHint: '',
    files: ['bootstrap.ts', 'agent/worker-process/child.ts', '__tests__/assembly-audit.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_MCP_APPROVAL',
    defaultHint: '',
    files: ['mcp/server-approval.ts', 'mcp/__tests__/manager.test.ts'],
    description: 'MCP 连接级审批门：gate 强制拦截、open 强制 fail-open；未设则按宿主是否有交互 UI 自动降级。',
  },
  {
    name: 'RIVET_MCP_LIVE',
    defaultHint: '',
    files: ['server/__tests__/mcp-presets.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_MCP_LOG_BYTES',
    defaultHint: '\'\'',
    files: ['mcp/log-buffer.ts', 'mcp/__tests__/log-buffer.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_MCP_OAUTH_CLIENT_ID',
    defaultHint: '\'\'',
    files: ['tui/slash-commands.ts', 'mcp/manager.ts'],
    description: '',
  },
  {
    name: 'RIVET_MCP_RECONNECT',
    defaultHint: '',
    files: ['mcp/manager.ts'],
    description: '',
  },
  {
    name: 'RIVET_MEMORY_AUTO_CAPTURE',
    defaultHint: '',
    files: ['memory/auto-capture.ts'],
    description: '记忆形成侧：重要操作后模型判断并写入 LTM；off/0 关闭，默认开启。',
  },
  {
    name: 'RIVET_MEMORY_BACKFILL',
    defaultHint: '',
    files: ['memory/backfill.ts'],
    description: '历史会话回填（opt-in）：启动 30s 后闲时补采存量会话的知识写 LTM（ledger 幂等，每轮 ≤5 会话）；1/on 开启，默认关闭。',
  },
  {
    name: 'RIVET_MEMORY_CONSOLIDATION',
    defaultHint: '',
    files: ['memory/session-consolidation.ts'],
    description: '会话结束巩固：生成会话摘要 + 可复用做法写入 LTM；off/0 关闭，默认开启。',
  },
  {
    name: 'RIVET_MEMORY_LIMIT_BYTES',
    defaultHint: '',
    files: ['agent/resource-sensor.ts', 'agent/__tests__/resource-sensor.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_MERIDIAN_BACKFILL',
    defaultHint: '',
    files: ['tools/__tests__/repo-graph-flow.test.ts', 'repo/meridian-backfill.ts', 'repo/__tests__/meridian-backfill.test.ts'],
    description: 'Meridian 后台全量索引总开关，设 0 整体关闭（默认开）',
  },
  {
    name: 'RIVET_MERIDIAN_BACKFILL_MAX',
    defaultHint: '',
    files: ['repo/meridian-backfill.ts', 'repo/__tests__/meridian-backfill.test.ts'],
    description: 'Meridian 后台全量索引的文件数上限（默认 2000）',
  },
  {
    name: 'RIVET_MISTAKE_NOTEBOOK',
    defaultHint: '',
    files: ['agent/p3-integration.ts', 'agent/__tests__/p3-integration.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_MOBILE_DIR',
    defaultHint: '',
    files: ['server/serve.ts'],
    description: 'serve 的 /mobile 静态挂载目录（P2 Mobile Remote）；配置后 /mobile 前缀在 auth 门前免 Bearer 服务该目录前端资产，未配则一律 404。CLI --mobile-dir 优先于本 env。',
  },
  {
    name: 'RIVET_NEIGHBOR_HINT',
    defaultHint: '',
    files: ['tools/read-file.ts', 'tools/__tests__/neighbor-hint.test.ts', 'agent/loop-factory.ts'],
    description: '',
  },
  {
    name: 'RIVET_NEW_SESSION',
    defaultHint: '',
    files: ['bootstrap.ts', 'main.ts'],
    description: '',
  },
  {
    name: 'RIVET_NO_AUTO_RESUME',
    defaultHint: '',
    files: ['bootstrap.ts'],
    description: '',
  },
  {
    name: 'RIVET_NO_CROSS_SESSION',
    defaultHint: '',
    files: ['agent/cross-session-memory-config.ts', 'agent/loop.ts', 'agent/__tests__/cross-session-killswitch.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_NO_EMBEDDINGS',
    defaultHint: '',
    files: ['search/embedding-provider.ts'],
    description: '',
  },
  {
    name: 'RIVET_NO_SYSTEM_PROXY',
    defaultHint: '',
    files: ['tui/__tests__/updater.test.ts', 'tools/net/proxy-resolver.ts', 'mcp/oauth/__tests__/request-security.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_NO_UPDATE_CHECK',
    defaultHint: '',
    files: ['main.ts'],
    description: '',
  },
  {
    name: 'RIVET_NOTIFY_BELL',
    defaultHint: '',
    files: ['tui/engine/app.ts'],
    description: '',
  },
  {
    name: 'RIVET_OAUTH_PORT',
    defaultHint: '',
    files: ['mcp/oauth/connector.ts', 'mcp/oauth/__tests__/request-security.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_OAUTH_TIMEOUT',
    defaultHint: '\'\'',
    files: ['auth/oauth-auth.ts'],
    description: '',
  },
  {
    name: 'RIVET_ORCHESTRATION_HINT',
    defaultHint: '',
    files: ['main.ts'],
    description: '',
  },
  {
    name: 'RIVET_OUTPUT_SANITIZE',
    defaultHint: '',
    files: ['agent/tool-execution.ts'],
    description: '',
  },
  {
    name: 'RIVET_PAL',
    defaultHint: '',
    files: ['tools/attack-case.ts', 'agent/hooks/problem-attack-hook.ts'],
    description: '',
  },
  {
    name: 'RIVET_PARENT_PID',
    defaultHint: '',
    files: ['server/serve.ts', 'server/__tests__/parent-watchdog.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PLAN_CONSTRAINTS',
    defaultHint: '',
    files: ['agent/plan-constraints.ts', 'agent/__tests__/plan-constraints.test.ts'],
    description: '设为 0 关闭计划约束自动注入（D8 L2），resolvePlanConstraints 恒返回 []',
  },
  {
    name: 'RIVET_PLAN_EXECUTE_TIMEOUT_MS',
    defaultHint: '',
    files: ['tools/plan-task.ts'],
    description: '',
  },
  {
    name: 'RIVET_PLAN_MODE_SUGGEST',
    defaultHint: '',
    files: ['agent/plan-mode-advisor.ts', 'agent/__tests__/plan-mode-advisor.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PLAYBOOK',
    defaultHint: '',
    files: ['bootstrap.ts', '__tests__/assembly-audit.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PLAYBOOK_INJECT',
    defaultHint: '',
    files: ['agent/context-injection.ts', 'agent/__tests__/playbook-injection-revival.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PREV_HANDOFF',
    defaultHint: '',
    files: ['agent/cross-session-memory-config.ts', 'agent/__tests__/cross-session-killswitch.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PRO',
    defaultHint: '',
    files: ['server/__tests__/recordings-distill-route.test.ts', 'pro/__tests__/register-gate.test.ts', 'config/pro-license.ts', 'config/__tests__/pro-license.test.ts'],
    description: '【仅 CLI 软 gate】开源版三路径之一（config > env > file）。桌面端（RIVET_DESKTOP=1）自 v3.21.1 起不再读取该变量——桌面端只认 shell 注入的签名凭证 RIVET_PRO_GRANT，裸 env/config/文件三条后门全部封死。',
  },
  {
    name: 'RIVET_PRO_DEVICE_ID',
    defaultHint: '',
    files: ['config/pro-license.ts', 'config/__tests__/pro-license.test.ts'],
    description: 'Tauri shell 注入的本机设备指纹（与 machine_uid 同源），用于与凭证 payload.deviceId 强比对。纵深防御：设备绑定的主判定在 Rust read_status（device_mismatch），此处只做交叉校验。',
  },
  {
    name: 'RIVET_PRO_GRANT',
    defaultHint: '',
    files: ['pro/__tests__/register-gate.test.ts', 'config/pro-license.ts', 'config/__tests__/pro-license.test.ts'],
    description: '桌面端 Pro 凭证：license-server 以 Ed25519 签名的许可证 token（base64url(payload).base64url(sig)），由 Tauri shell 在「验签 + 运行时完整性校验 + is_pro()」全通过后注入；sidecar 用编译进包的公钥验签并校验产品/时间窗/设备。伪造需要签发私钥，故 env 注入类攻击（命令行直启、Frida hook CreateProcessW、父进程继承）失效。',
  },
  {
    name: 'RIVET_PROBE_DISCIPLINE',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_PROBE_TRACKING',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_PROFILE',
    defaultHint: '',
    files: ['config/profile.ts', 'config/__tests__/config-watcher.test.ts', 'config/__tests__/manager-profile-persist.test.ts', 'cli/early-routing.ts', 'cli/__tests__/early-routing.test.ts', 'agent/__tests__/config-watcher-release.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PROMPT_PROFILE',
    defaultHint: 'profile',
    files: ['prompt/block-policy.ts', 'prompt/__tests__/block-policy.test.ts', 'config/__tests__/runtime-lean.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_PROMPT_TOOL_DESC',
    defaultHint: 'toolDescriptions',
    files: ['prompt/block-policy.ts'],
    description: '',
  },
  {
    name: 'RIVET_READ_REF',
    defaultHint: '',
    files: ['tools/read-file.ts', 'tools/__tests__/read-file-dedup.test.ts', 'tools/__tests__/read-file-invalidation.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_REASONING_SPIRAL_GUARD',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_REGRESSION_BISECT',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_RELIABILITY_OVERRIDE',
    defaultHint: '',
    files: ['agent/loop.ts'],
    description: '',
  },
  {
    name: 'RIVET_RENDER_VERIFY',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts', 'agent/deliver-task.ts'],
    description: '',
  },
  {
    name: 'RIVET_REPLAY_COMPACT',
    defaultHint: '',
    files: ['server/replay-compaction.ts', 'server/__tests__/session-history-page.test.ts', 'server/__tests__/session-replay-compaction.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_REPO_GRAPH',
    defaultHint: '',
    files: ['bootstrap.ts'],
    description: '',
  },
  {
    name: 'RIVET_RESUME',
    defaultHint: '',
    files: ['bootstrap.ts', 'main.ts'],
    description: '',
  },
  {
    name: 'RIVET_RESUME_ID',
    defaultHint: '',
    files: ['bootstrap.ts', 'main.ts'],
    description: '',
  },
  {
    name: 'RIVET_REVIEW_DISCIPLINE',
    defaultHint: '',
    files: ['config/review-discipline-config.ts'],
    description: '',
  },
  {
    name: 'RIVET_RIPGREP_PATH',
    defaultHint: '',
    files: ['tools/grep.ts'],
    description: '',
  },
  {
    name: 'RIVET_RTK',
    defaultHint: '',
    files: ['tools/bash.ts', 'tools/__tests__/bash.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_RUNTIME_ENV',
    defaultHint: '',
    files: ['prompt/runtime-env.ts', 'prompt/__tests__/runtime-env.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_SANDBOX',
    defaultHint: '',
    files: ['tools/bash.ts', 'tools/sandbox-profile.ts', 'tools/__tests__/sandbox-profile.test.ts'],
    description: '追加可写根目录，平台分隔符分隔（POSIX 用 :，Windows 用 ;）。与工具链画像、会话授权合并。',
  },
  {
    name: 'RIVET_SANDBOX_WRITABLE',
    defaultHint: '',
    files: ['tools/sandbox-profile.ts'],
    description: '',
  },
  {
    name: 'RIVET_SCOUT_FIREWALL',
    defaultHint: '',
    files: ['config/scout-firewall-config.ts', 'config/__tests__/scout-firewall-config.test.ts', 'agent/__tests__/deliver-task.test.ts'],
    description: '证据防火墙 Phase 2：deliver_task commit 引用未核验 scout 断言时 isError 硬拦，默认关（opt-in）；设 1/true/on 开启，0/false/off 强制关（等价 config agent.scoutEvidenceFirewall）',
  },
  {
    name: 'RIVET_SCRIPT_ITERATION_DETECTOR',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_SEARCH_POD',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_SECURITY_GUIDANCE',
    defaultHint: '',
    files: ['config/security-guidance-config.ts', 'agent/__tests__/create-runtime-hooks.test.ts'],
    description: '安全模式正则告警（层1）总开关，默认开；设 0/false/off/no 关闭（等价 config agent.securityGuidance=false）',
  },
  {
    name: 'RIVET_SERVE_HOST',
    defaultHint: '',
    files: ['server/serve.ts'],
    description: 'serve 监听地址（默认 127.0.0.1）；LAN IP/0.0.0.0 开启远程访问（P1 Mobile Remote）。CLI --host 优先于本 env。',
  },
  {
    name: 'RIVET_SERVE_HOSTS_ALLOW',
    defaultHint: '',
    files: ['server/serve.ts'],
    description: 'serve Host header allowlist（逗号分隔，不带端口）；配置后非回环 Host 仅白名单放行（DNS-rebinding 防护恢复）。全条目非法时告警并按未配置处理。',
  },
  {
    name: 'RIVET_SERVE_TIMING',
    defaultHint: '',
    files: ['server/serve-timing.ts', 'server/serve.ts', 'server/session-routes.ts'],
    description: 'sidecar 启动阶段时间线 `[serve-timing] phase=<name> +<ms>`（start / pro-module / rehydrate / routes / listen / warm-start / plugins-warm / serve-agent-loaded / mcp）。未设：生产默认开、ephemeral（测试）默认关；`0` 全关；`1` 强开并附带 serve-agent import 耗时与小回放的 replay 计时等冗长行。',
  },
  {
    name: 'RIVET_SERVE_WARM_DELAY_MS',
    defaultHint: '',
    files: ['server/serve-timing.ts'],
    description: 'sidecar listen 后到预热（agent 装配 chunk import + 插件快照）点火的延迟毫秒数；`0` = listen 后立即（旧行为）。首个会话的 createAgent 无论如何都会即时拉响预热，本值只影响空闲启动期与首批 UI 请求抢 CPU 的窗口。',
  },
  {
    name: 'RIVET_SERVER_TOKEN',
    defaultHint: '',
    files: ['server/serve.ts'],
    description: '',
  },
  {
    name: 'RIVET_SESSION_DIR',
    defaultHint: '',
    files: ['server/__tests__/cache-routes.test.ts', 'server/__tests__/fork.test.ts', 'server/__tests__/handoff-route.test.ts', 'server/__tests__/serve-restore-history.test.ts', 'server/__tests__/session-delete-cleanup.test.ts', 'server/__tests__/session-routes.test.ts', 'server/__tests__/snapshot.test.ts', 'prompt/__tests__/frozen-snapshot-persist.test.ts', 'diagnostics/__tests__/log-locations.test.ts', 'config/paths.ts', 'agent/__tests__/appendix-trace.test.ts', 'agent/__tests__/handoff-persist.test.ts', 'agent/__tests__/loop-factory.test.ts', 'agent/__tests__/persist-integration.test.ts', 'agent/__tests__/session-cd-rebuild-stores.test.ts', 'agent/__tests__/session-cd.test.ts', 'agent/__tests__/session-persist-codec.test.ts', 'agent/__tests__/session-persist.test.ts', 'agent/__tests__/speculation-stats-meta.test.ts', 'agent/__tests__/tool-pipeline.test.ts', 'agent/__tests__/worker-session.test.ts', '__tests__/bootstrap.test.ts', '__tests__/switch-agent-session.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_SIDECAR_ENTRY',
    defaultHint: '',
    files: ['server/plugin-api.ts'],
    description: '',
  },
  {
    name: 'RIVET_SKILL_GATE',
    defaultHint: '',
    files: ['agent/skill-gate.ts', 'agent/__tests__/skill-gate.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_SKIP_STAGED_RUNTIME_CHECK',
    defaultHint: '',
    files: ['platform/staged-runtime-guard.ts'],
    description: '',
  },
  {
    name: 'RIVET_SPEC_OBSERVE',
    defaultHint: '',
    files: ['agent/loop-factory.ts', 'agent/loop.ts', 'agent/__tests__/llm-speculation-wiring.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_STREAM_RESULT_MAX',
    defaultHint: '',
    files: ['stream-json.ts', '__tests__/stream-json.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TDD_GATE',
    defaultHint: '\'\'',
    files: ['agent/tdd-gate.ts', 'agent/__tests__/tdd-gate.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TELEMETRY_LITE',
    defaultHint: '',
    files: ['agent/frame-telemetry.ts', 'agent/telemetry-writer.ts', 'agent/__tests__/frame-telemetry.test.ts', 'agent/__tests__/telemetry-writer.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TERSE',
    defaultHint: '',
    files: ['prompt/__tests__/terseness-nudge.test.ts', '__tests__/assembly-audit.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TEST',
    defaultHint: '',
    files: ['agent/coordinator.ts'],
    description: '',
  },
  {
    name: 'RIVET_TEST_CANDIDATE_KEY',
    defaultHint: '',
    files: ['agent/__tests__/candidate-models.test.ts'],
    description: '仅测试用：候选池凭据过滤测试的假 API key 注入点，生产代码不读',
  },
  {
    name: 'RIVET_TEST_ENV_KEY_PROV',
    defaultHint: '',
    files: ['server/__tests__/serve-switch-model.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TEST_GLM_KEY',
    defaultHint: '',
    files: ['__tests__/switch-agent-session.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TEST_PRESENCE_GATE',
    defaultHint: '',
    files: ['agent/test-presence.ts', 'agent/__tests__/deliver-task.test.ts', 'agent/__tests__/test-presence.test.ts', 'agent/__tests__/wave-gate.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TOKEN_STORE',
    defaultHint: '',
    files: ['config/__tests__/secrets-store.test.ts', 'auth/secure-store.ts', 'auth/__tests__/secure-store.test.ts'],
    description: '凭据落盘加密的数据密钥托管后端：keychain(macOS 默认) / dpapi(Windows 默认) / local-key(Linux 默认，仅混淆不是安全边界) / plaintext(显式关闭加密，仅排障)。密钥库不可用时自动降级到 local-key 并打 warn。',
  },
  {
    name: 'RIVET_TOOL_PRESET',
    defaultHint: '',
    files: ['tools/tool-preset.ts', 'tools/__tests__/tool-preset.test.ts', 'config/__tests__/runtime-lean.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TRUST_PROJECT',
    defaultHint: '',
    files: ['main.ts', 'tools/__tests__/monitor-tool.test.ts', 'tools/__tests__/run-tests-declared.test.ts', 'server/__tests__/hooks-route.test.ts', 'server/__tests__/mcp-server-config.test.ts', 'server/__tests__/serve-agent-config-merge.test.ts', 'server/__tests__/session-manager.test.ts', 'server/__tests__/trust-api.test.ts', 'prompt/__tests__/engine.test.ts', 'prompt/__tests__/project-instructions.test.ts', 'prompt/__tests__/volatile.test.ts', 'config/__tests__/layered-config.test.ts', 'config/__tests__/project-trust.test.ts', 'config/__tests__/verify-config.test.ts', 'agent/__tests__/typecheck-gate.test.ts', 'agent/__tests__/user-hooks-bridge.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TS_LOAD_TIMEOUT',
    defaultHint: '\'\'',
    files: ['tools/syntax-check.ts'],
    description: 'syntax-check 加载 esbuild 的超时（ms；0/负数回退 3s）',
  },
  {
    name: 'RIVET_TS_PARSE_TIMEOUT',
    defaultHint: '\'\'',
    files: ['tools/syntax-check.ts', 'tools/__tests__/syntax-check.test.ts'],
    description: 'tree-sitter Python 语法校验的加载+解析超时(ms),缺省 5000',
  },
  {
    name: 'RIVET_TSC_FALLBACK_TIMEOUT',
    defaultHint: '\'\'',
    files: ['tools/syntax-check.ts'],
    description: '',
  },
  {
    name: 'RIVET_TUI_HARDWARE_CURSOR',
    defaultHint: '',
    files: ['tui/engine/live-engine.ts', 'tui/engine/__tests__/live-engine.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TURN_BUDGET_WARN',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_TYPECHECK_GATE',
    defaultHint: '',
    files: ['agent/typecheck-gate.ts', 'agent/__tests__/typecheck-gate.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TYPECHECK_REPO_WIDE',
    defaultHint: '',
    files: ['agent/typecheck-gate.ts', 'agent/__tests__/typecheck-gate.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_TYPECHECK_SHARE',
    defaultHint: '',
    files: ['tools/bash.ts', 'lsp/client.ts'],
    description: '',
  },
  {
    name: 'RIVET_VERSION',
    defaultHint: '\'0.0.0-dev\'',
    files: ['server/serve.ts', 'api/provider-catalog.ts'],
    description: '',
  },
  {
    name: 'RIVET_VSW',
    defaultHint: '',
    files: ['bootstrap.ts'],
    description: '',
  },
  {
    name: 'RIVET_WAVE_GATE',
    defaultHint: '',
    files: ['tools/__tests__/plan-task.test.ts', 'agent/wave-gate.ts', 'agent/__tests__/plan-executor.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WEB_CRAWL',
    defaultHint: '',
    files: ['tools/default-registry.ts'],
    description: '',
  },
  {
    name: 'RIVET_WEB_MAP',
    defaultHint: '',
    files: ['tools/default-registry.ts'],
    description: '',
  },
  {
    name: 'RIVET_WELCOME_ANIM',
    defaultHint: '',
    files: ['main.ts'],
    description: '',
  },
  {
    name: 'RIVET_WELCOME_GREETING',
    defaultHint: '',
    files: ['tui/welcome-greeting.ts', 'tui/__tests__/welcome-greeting.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WELCOME_LOGO',
    defaultHint: '',
    files: ['tui/format/welcome.ts', 'tui/__tests__/format-welcome.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WHISPER_BIN',
    defaultHint: '',
    files: ['server/speech-routes.ts', 'server/__tests__/speech-routes.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WHISPER_FETCH_SCRIPT',
    defaultHint: '',
    files: ['server/speech-routes.ts', 'server/__tests__/speech-routes.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WHISPER_MODEL',
    defaultHint: '',
    files: ['server/speech-routes.ts', 'server/__tests__/speech-routes.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WHISPER_PROXY',
    defaultHint: '',
    files: ['server/speech-routes.ts', 'server/__tests__/speech-routes.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WORKER_BUDGET_HISTORY',
    defaultHint: '',
    files: ['agent/budget-shape.ts', 'agent/__tests__/budget-shape.test.ts'],
    description: '=0 关闭写工预算的历史实际用量地板（同 objective 的 worker_actual 样本不再抬升预算）',
  },
  {
    name: 'RIVET_WORKER_BUDGET_SHAPE',
    defaultHint: '',
    files: ['agent/budget-shape.ts', 'agent/__tests__/budget-shape.test.ts'],
    description: '=0 关闭写工预算的文件形状定价（48 轮/600s flat 默认回归）',
  },
  {
    name: 'RIVET_WORKER_FINALIZE',
    defaultHint: '',
    files: ['agent/coordinator.ts'],
    description: '',
  },
  {
    name: 'RIVET_WORKER_ISOLATION',
    defaultHint: '',
    files: ['agent/worker-process/parent.ts', 'agent/worker-process/__tests__/worker-process.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WORKER_WRITE_GATE',
    defaultHint: '',
    files: ['agent/worker-write-gate.ts', 'agent/__tests__/hands-session.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WRAPUP_ANXIETY_GUARD',
    defaultHint: '',
    files: ['agent/create-runtime-hooks.ts'],
    description: '',
  },
  {
    name: 'RIVET_WRITE_OVERWRITE_GUARD',
    defaultHint: '',
    files: ['tools/write-file.ts', 'tools/__tests__/write-file.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_WRITE_PROBE',
    defaultHint: '',
    files: ['context/write-evidence-probe.ts', 'context/__tests__/write-evidence-probe.test.ts'],
    description: '',
  },
  {
    name: 'RIVET_X',
    defaultHint: '',
    files: ['__tests__/assembly-audit.test.ts'],
    description: '',
  },
]
